Class duplicate validation error fix
AlexWebLab/bootstrap-5-wordpress-navbar-walker pull request #4
Opened 2021-05-04 11:20 UTC by asifpix

Now this walker will output class only once.

2021-05-05 01:57 UTC, AlexWebLab requested changes
how about to replace this:
`$item_output .= ($depth > 0) ? '<a' . $attributes . '>' : '<a' . $attributes . '>';`
with this:
`$item_output .= '<a' . $attributes . '>';`

2021-05-06 07:48 UTC, AlexWebLab approved these changes

2021-05-06 07:49 UTC, merged

2021-05-06 07:58 UTC, AlexWebLab commented
I've also replaced this:
`$nav_link_class = ( $depth > 0 ) ? 'dropdown-item nav-link ' : 'nav-link ';`
with this:
`$nav_link_class = ( $depth > 0 ) ? 'dropdown-item ' : 'nav-link ';`
because, according to the official documentation, when an anchor tag is grandchild of a _.dropdown-menu_ class then it has only _.dropdown-item_ class and not _.nav-link_ class.

2021-05-06 09:04 UTC, asifpix commented
Thanks for the fix. I am removing the fork.